extends: google

parserOptions:
  ecmaVersion: 6

rules:
  require-jsdoc: 0
  quotes: ["error", "double"]
  no-throw-literal: 0
  eol-last: 0
  guard-for-in: 0
  comma-dangle: 0
  prefer-const: 0
  indent: 0
  operator-linebreak: ["error", "before"]
  linebreak-style: 0
  max-len: ["error", { "code": 130 }]